# Generated by Django 3.1.2 on 2021-02-20 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=600)),
                ('shared_link', models.CharField(max_length=6000)),
                ('title', models.CharField(max_length=1200)),
                ('description', models.TextField(max_length=3200)),
                ('tags', models.TextField(max_length=1600)),
                ('status', models.CharField(default='PB', max_length=2)),
                ('suspended', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1600)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reported', to='App0.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.TextField(default='', max_length=1600)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Teeker/profiles/')),
                ('banner_picture', models.ImageField(blank=True, null=True, upload_to='Teeker/banners/')),
                ('suspended', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('developer', models.BooleanField(default=False)),
                ('founder', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=False)),
                ('socialmedialinks', models.TextField(blank=True, default='', null=True)),
                ('recommended', models.TextField(blank=True, default='', null=True)),
                ('user_chasing', models.TextField(blank=True, default='', null=True)),
                ('user_blocked', models.TextField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents_history', to='App0.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=999999)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to='App0.content')),
            ],
        ),
    ]
