# Generated by Django 3.1.1 on 2020-09-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='history',
            name='report_flag',
        ),
    ]
