# Generated by Django 3.1.1 on 2020-09-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0003_auto_20200925_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=999999),
        ),
    ]
