# Generated by Django 3.1.2 on 2020-10-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0004_auto_20200925_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_blocked',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
