# Generated by Django 3.1.2 on 2021-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0005_profile_user_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teeker/profiles/banner_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teeker/profiles/display_pictures/'),
        ),
    ]
