# Generated by Django 3.1.2 on 2021-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0006_auto_20210126_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
