# Generated by Django 3.1.2 on 2021-02-04 15:18

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0009_auto_20210204_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='Profile_Pictures'),
            preserve_default=False,
        ),
    ]
