# Generated by Django 3.1.2 on 2021-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App0', '0010_auto_20210204_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Teeker/profiles/'),
        ),
    ]
